### 02. 텐서 조작하기(Tensor Manipulation) 1

Vector, Matrix, Tensor
    - 딥러닝을 위한 가장 기본적인 수학적 지식
- Numpy Review
    - 파이토치는 파이썬 패키지 넘파이와 유사하므로 넘파이에 대해서 간단히 공부
- PyTorch Tensor Allocation
    - 넘파이로 실습한 후 파이토치 텐서 선언 방법에 대해서 공부
- Matrix Multiplication
    - 행렬 연산에 대해서 공부
- Other Basic Ops
    - 다른 기본적인 오퍼레이션들에 대해서 공부

-----------------------------------------------------------------------------------------------------------

#### 1. Vector, Matrix, Tensor

##### 1) 그림으로 이해하기

##### 2) Pytorch Tensor Shape Convention

- 2D tensor : (Batch size, dim)
- 3D tensor(computer vision) : (batch size, width, height)
- 3D tensor(NL) : (batch size, length, dim)

- 3D tensor example(NLP)
    - 4개의 문장 : [[나는 사과를 좋아해], [나는 바나나를 좋아해], [나는 사과를 싫어해], [나는 바나나를 싫어해]]
    - 단어별로 나누기 : [['나는', '사과를', '좋아해'], ['나는', '바나나를', '좋아해'], ['나는', '사과를', '싫어해'], ['나는', '바나나를', '싫어해']] -> 4X3의 크기를 가지는 2D 텐서
    - 각 단어를 벡터로 만들기 
        - '나는' = [0.1, 0.2, 0.9]
        - '사과를' = [0.3, 0.5, 0.1]
        - '바나나를' = [0.3, 0.5, 0.2]
        - '좋아해' = [0.7, 0.6, 0.5]
        - '싫어해' = [0.5, 0.6, 0.7]
    - 훈련 데이터를 재구성 : [[[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.7, 0.6, 0.5]],
                             [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.7, 0.6, 0.5]],
                             [[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.5, 0.6, 0.7]],
                             [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.5, 0.6, 0.7]]] 
                             -> 4x3x3의 크기를 가지는 3D 텐서 
    - batch size를 2로 : [[[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.7, 0.6, 0.5]],
                          [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.7, 0.6, 0.5]]]
                         [[[[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.5, 0.6, 0.7]],
                          [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.5, 0.6, 0.7]]] 
                             

-----------------------------------------------------------------------------------------------------------

#### 2. 넘파이로 텐서 만들기(벡터와 행렬 만들기)

방법 : [숫자, 숫자, 숫자]와 같은 형식으로 만들고 이를 np.array()로 감싸주는 간단한 방법

In [2]:
import numpy as np

##### 1) 1D with Numpy

In [4]:
# 파이썬으로 설명하면 list를 생성해서 np.array로 1차원 array로 변환
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)    

[0. 1. 2. 3. 4. 5. 6.]


In [8]:
# 1차원 텐서인 벡터의 차원과 크기 출력
print('Rank of t : ', t.ndim)
print('Shape of t : ', t.shape)

Rank of t :  1
Shape of t :  (7,)


In [ ]:
##### 1-1) 넘파이 기초 이해하기

In [9]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1])

t[0] t[1] t[-1] =  0.0 1.0 6.0


In [10]:
print('t[2:5] t[4:-1] = ', t[2:5], t[4:-1])

t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5.]


In [11]:
print('t[:2] t[3:]   = ', t[:2], t[3:])

t[:2] t[3:]   =  [0. 1.] [3. 4. 5. 6.]


##### 2) 2D with Numpy(Matrix)

In [16]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [17]:
print('Rank of t : ', t.ndim)
print('Shape of t : ', t.shape)

Rank of t :  2
Shape of t :  (4, 3)


-----------------------------------------------------------------------------------------------------------

#### 3. 파이토치 텐서 선언하기(PyTorch Tensor Allocation)

In [18]:
import torch

##### 1) 1D with PyTorch

In [19]:
t = torch.FloatTensor([0., 1., 2., 3., 4. ,5. ,6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [22]:
print(t.dim())
print(t.shape)
print(t.size())

1
torch.Size([7])
torch.Size([7])


In [23]:
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


##### 2) 2D with PyTorch

In [24]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [25]:
print(t.dim())
print(t.size())

2
torch.Size([4, 3])


In [26]:
print(t[:, 1])
print(t[:, 1].size())

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [27]:
print(t[:, :-1])

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


##### 3) 브로드캐스팅(Broadcasting)

In [32]:
# 같은 크기일 때 연산
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1+m2)

tensor([[5., 5.]])


In [35]:
# 다른 크기일 때 연산(스칼라+벡터)
m1 = torch.FloatTensor([[1,2]]) 
m2 = torch.FloatTensor([3]) 
print(m1+m2)

tensor([[4., 5.]])
torch.Size([1, 2])
torch.Size([1])


In [36]:
# 다른 크기일 때 연산(벡터간)
m1 = torch.FloatTensor([[1,2]]) # 1x2
m2 = torch.FloatTensor([[3], [4]]) # 2x1
print(m1+m2) # 2x2

tensor([[4., 5.],
        [5., 6.]])


##### 4) 자주 사용되는 기능들

##### 4-1) 행렬 곱셈(.matmul)과 원소 별 곱셈(.mul)의 차이 

In [38]:
# 파이토치의 행렬 곱셈(.matmul)
m1 = torch.FloatTensor([[1., 2.], [3., 4.]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1 : ', m1.shape)
print('Shape of Matrix 2 : ', m2.shape)
print(m1.matmul(m2))

Shape of Matrix 1 :  torch.Size([2, 2])
Shape of Matrix 2 :  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [39]:
# 원소 별 곱셈(.mul)
m1 = torch.FloatTensor([[1., 2.], [3., 4.]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1 : ', m1.shape)
print('Shape of Matrix 2 : ', m2.shape)
print(m1 * m2) 
print(m1.mul(m2))

Shape of Matrix 1 :  torch.Size([2, 2])
Shape of Matrix 2 :  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


##### 4-2) 평균

In [40]:
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [44]:
t = torch.FloatTensor([[1,2], [3,4]])
print(t)
print(t.mean())

tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)


In [45]:
# dim=0은 첫번째 차원(행)을 의미
# dim이라는 인자를 준다면 해당 차원을 제거한다는 의미 -> 열만 남기겠다. 
print(t.mean(dim=0))

tensor([2., 3.])


In [46]:
# dim=1은 첫번째 차원(열)을 의미
# dim이라는 인자를 준다면 해당 차원을 제거한다는 의미 -> 행만 남기겠다. 
print(t.mean(dim=1))

tensor([1.5000, 3.5000])


In [47]:
# dim=-1은 마지막 차원을 제거한다는 의미로 열의 차원을 제거
print(t.mean(dim=-1))

tensor([1.5000, 3.5000])


##### 4-3) 덧셈

In [48]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [51]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


##### 4-4) 최대(Max)와 아그맥스(ArgMax)

- 최대(Max) : 원소의 최대값을 리턴
- 아그맥스(ArgMax) : 최댓값을 가진 인덱스를 리턴

In [52]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [53]:
print(t.max())

tensor(4.)


In [60]:
# max에 dim인자를 주면 argmax도 함께 리턴한다. 
# 행 제거
print(t.max(dim=0))

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [56]:
# max, argmax 둘 중 하나만 리턴하고 싶다면, 리턴값에도 인덱스를 부여
# 0번 인덱스 -> max값만
# 1번 인덱스 -> argmax값만
print('Max : ', t.max(dim=0)[0])
print('Argmax : ', t.max(dim=0)[1])

Max :  tensor([3., 4.])
Argmax :  tensor([1, 1])


In [59]:
# max에 dim인자를 주면 argmax도 함께 리턴한다. 
# 열 제거
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


-----------------------------------------------------------------------------------------------------------

- 데이터 사이언스 분야 한정으로 3차원 이상의 텐서는 다차원 행렬(배열)로 간주 할 수 있다. 또한 3차원 이상을 텐서라고 하지만 1차원 벡터나 2차원 행렬도 텐서라고 표현하기도 한다. 
    - 벡터 = 1차원 텐서, 2차원 행렬 = 2차원 텐서, 3차원 텐서, 4차원 텐서 등
- 훈련 데이터 하나의 크기를 256이라고 한다면 [3, 1, 2, 5, 10, ...] 이런 숫자들의 나열이 256 길이로 있다고 상상하면 된다. 다시 말해 훈련 데이터 하나 = 벡터의 차원 = 256
    - 만약 이런 훈련 데이터의 개수가 3000개라고 한다면 현재 전체 훈련 데이터의 크기는 3000 x 256 -> 행렬(2D 텐서)
    - 3000개를 1개씩 꺼내서 처리하는 것도 가능하지만 컴퓨터는 훈련 데이터를 하나씩 처리하는 것보다 보통 덩어리로 처리
    - 3000개에서 64개씩 꺼내서 처리한다고 한다면 batch size를 64라고 한다.
    - 이렇게 되면 컴퓨터가 한 번에 처리하는 2D 텐서의 크기는 (batch size x dim) = 64 x 256
- 텐서의 크기(shape)를 표현할 때, ,(컴마)를 쓰기도 하고 x(곱하기)를 쓰기도 한다.
    - 예를 들어 2행 3열의 2D 텐서를 표현할 때 (2,3) or (2x3)
    - (5,)의 형식은 (1,5)를 의미한다.
- 훈련 데이터의 개수가 굉장히 많을 떄, 컴퓨터가 한번에 들고가서 처리할 양을 배치 크기(batch size)라고 한다.