### 02. 텐서 조작하기(Tensor Manipulation) 2

##### 4) 뷰(View) - 원소의 수를 유지하면서 텐서의 크기 변경(매우 중요)

- 파이토치 텐서의 뷰(View)는 넘파이에서 리쉐이프(Reshpae)와 같은 역할을 한다.
- 텐서의 크기(Shape)를 변경해주는 역할

In [2]:
import numpy as np
import torch
t = np.array([[[0., 1., 2.],
               [3., 4., 5.]],
              [[6., 7., 8.],
               [9., 10., 11]]])
ft = torch.FloatTensor(t)

In [5]:
print(ft.shape)
print(t.shape)

torch.Size([3])
(2, 2, 3)


##### 4-1) 3차원 텐서에서 2차원 텐서로 변경
- view([-1, 3])의 의미
    - -1 : 첫번째 차원은 사용자가 잘 모르겠으니 파이토치에 맡기겠다
    - 3 : 두번째 차원의 길이는 3을 가지도록 하라는 의미
    - 다시 말해 현재 3차원 텐서를 2차원 텐서로 변경하되 (?, 3)의 크기로 변경하라 -> (4,3)의 크기를 가지는 텐서를 얻음
- 규칙
    - view는 기본적으로 변경 전과 변경 후의 텐서 안의 원소의 개수가 유지되어야 한다.
    - 파이토치의 view는 사이즈가 -1로 설정되면 다른 차원으로부터 해당 값을 유추해야 한다.

In [6]:
# ft라는 텐서를 (?, 3)의 크기로 변경
print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


##### 4-2) 3차원 텐서의 크기 변경
- 3차원 텐서에서 3차원 텐서로 차원은 유지하되, 크기(shape)를 바꾸기
- view로 텐서의 크기를 변경하더라도 원소의 수는 유지되어야 하므로 (2x2x3) -> (?x1x3) 텐서가 되려면 ?는 4가 되어야 한다.

In [7]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[0., 1., 2.]]])
torch.Size([1, 1, 3])


----------------------------------------------------------------------------------------------------------

##### 5) 스퀴즈(Squeeze) : 1인 차원을 제거한다.

In [8]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)
print(ft.dim())

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
2


In [9]:
# 두번째 차원이 1이므로 squeeze를 사용하면 (3,)의 크기를 가지는 텐서로 변경 -> 1차원 벡터로!
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


----------------------------------------------------------------------------------------------------------

##### 6) 언스퀴즈(Unsqueeze) : 특정 위치에 1인 차원을 추가한다.

In [10]:
# (3,)의 크기를 가지는 1인 차원 텐서 임의로 생성
ft = torch.Tensor([0,1,2])
print(ft.shape)

torch.Size([3])


In [11]:
print(ft.unsqueeze(0)) # 0은 첫번째 차원을 의미한다.
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [12]:
# 앞에서 배운 view로도 구현 가능 -> -1의 값이 3이 되어야 한다.
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [15]:
# unsqueeze의 인자로 -1(인덱스 상으로 마지막 차원) 넣기
# 현재 크기는 (3,)이므로 마지막 차원에 1인 차원을 추가하면 (3,1)의 크기를 가진다.
# 즉, 현재 텐서의 경우 1을 넣은 경우와 -1을 넣은 경우의 결과가 동일
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


- view(), squeeze(), unsqueeze()는 텐서의 원소 수를 그대로 유지하면서 모양과 차원을 조절한다.

----------------------------------------------------------------------------------------------------------

##### 7) 타입 캐스팅(Type Casting)

- 텐서에는 자료형이라는 것이 있다. 각 데이터형별로 정의되어져 있는데,
    - ex) 32비트의 부동 소수점은 torch.FloatTensor, 64비트 부호 있는 정수는 torch.LongTensor를 사용한다.
- GPU 연산을 위한 자료형도 있다.
    - ex) torch.cuda.FloatTensor
- 자료형을 변환하는 것을 타입 캐스팅이라고 한다. 

In [16]:
# long 타입의 lt라는 텐서를 선언
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [17]:
# 텐서에다가 .float()를 붙이면 바로 float형 타입으로 변경
print(lt.float())

tensor([1., 2., 3., 4.])


In [18]:
# Byte 타입의 bt라는 텐서를 선언
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [19]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


----------------------------------------------------------------------------------------------------------

##### 8) 연결하기(concatenate)
- 두 텐서를 연결하는 방법

In [23]:
# (2x2) 크기의 텐서를 두 개 만든다.
x = torch.FloatTensor([[1,2], [3,4]])
y = torch.FloatTensor([[5,6], [7,8]])

- torch.cat은 어느 차원을 늘릴 것인지를 인자로 줄 수 있다.

In [25]:
# 1. dim=0 : 첫번째 차원을 늘리라는 의미 -> 행
print(torch.cat([x, y], dim=0))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [27]:
# 2. dim=1 : 두번째 차원을 늘리라는 의미 -> 열
print(torch.cat([x, y], dim=1))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


- 딥러닝에서는 주로 모델의 입력 또는 중간 연산에서 두 개의 텐서를 연결하는 경우가 많다.
- 두 텐서를 연결해서 입력으로 사용하는 것은 두 가지의 정보를 모두 사용한다는 의미 !

----------------------------------------------------------------------------------------------------------

##### 9) 스택킹(Stacking)
- 연결(concatenate)을 하는 또 다른 방법
- 쌓는다는 의미
- 때로는 연결하는 것보다 스택킹이 더 편리할 때가 있는데, 이는 스택킹이 많은 연산을 포함하고 있기 때문

In [29]:
# 크기가 (2,)로 모두 동일한 3개의 벡터를 만든다.
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

In [30]:
# 1. 첫번째 차원이 증가한다.
print(torch.stack([x,y,z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [36]:
# 위의 코드와 동일한 결과를 갖는다(즉, 스택킹이 많은 연산을 한번에 축약하고 있음)
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [37]:
# 2. dim이라는 인자를 주어서 두번째 차원이 증가하도록
print(torch.stack([x,y,z], dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


----------------------------------------------------------------------------------------------------------

##### 10) ones_like와 zeros_like : 0으로 채워진 텐서와 1로 채워진 텐서

In [38]:
# (2x3) 텐서를 만든다.
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [39]:
print(torch.ones_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [40]:
print(torch.zeros_like(x))

tensor([[0., 0., 0.],
        [0., 0., 0.]])


----------------------------------------------------------------------------------------------------------

##### 11) In-place Onperation(덮어쓰기 연산)

In [41]:
# (2x2) 텐서를 만들고 x에 저장
x = torch.FloatTensor([[1, 2], [3, 4]])

In [42]:
# 곱하기 2를 수행한 결과를 출력
print(x.mul(2.)) 
# 기존의 값을 출력
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [43]:
# 연산 뒤에 _를 붙이면 기존의 값을 덮어쓰기 한다.
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
