#### 🔎 2.5.1 함수

- 주어진 문제에서 반복적인 연산이 나올 때 해당 연산을 함수로 만들어 사용

In [1]:
import numpy as np

def sincos(x) :
    return np.sin(x) + np.cos(x)

sincos(1)

1.3817732906760363

----------------------------------------------------------------------------------------------------------

#### 🔎 2.5.2 모듈

- 한 파일 내에 많은 기능들을 구현한다면 코드가 복잡해지며 지저분해진다.
- 기능에 따라 파일을 별도로 만들어 전체적인 코드 완성
- 모듈 : 전역 변수, 함수 등을 포함한 별도의 파일

----------------------------------------------------------------------------------------------------------

#### 🔎 2.5.3 클래스

- 하나의 기능을 구현하는데 여러개의 함수가 필요할 때
- 데이터와 세부적인 기능을 수행하는 함수들을 묶어서 구현

- `__init__( )` 
    - 클래스 내부에 외부 변수를 불러올 때 사용하는 함수
    - 괄호 안에 반드시 self 넣어주고 추가적으로 원하는 변수 나열 
    - 인스턴스가 실행될 때마다 자동으로 실행되는 메서드
- `def 함수(self)`
    - 클래스 내부의 함수에는 self를 반드시 기입한다.
    - 변수에서 self를 붙여 선언할 수 있다. (self를 붙인 변수는 클래스 내부의 함수들에서 별도의 선언 없이 자유롭게 사용 가능)
- `return self` 
    - 단순히 메서드(함수)가 호출된 인스턴스 개체에 대한 참조를 반환한다는 것을 의미

In [2]:
import numpy as np

class DataPreprocessing :
    def __init__(self, data, target) :
        self.data = data
        self.target = target
        self.num_instances = self.data.shape[0]
        self.num_features = self.data.shape[1]
    def minmax(self) :
        for i in range(self.num_features) :
            col = self.data[:, i]
            self.data[:, i] = (self.data[:, i] - np.min(col))/(np.max(col) - np.min(col))
        return self
    def normalization(self) :
        for i in range(self.num_features) :
            col = self.data[:, i]
            mu, sigma = np.mean(col), np.std(col)
            self.data[:, i] = (self.data[:, i]-mu)/sigma
        return self
    def scaler(self, scaling=None):
        if scaling == 'minmax' :
            self.minmax()
        elif scaling == 'standard' :
            self.normalization()
        else :
            pass
        return self.data        

##### 💡 **클래스 불러오기**
- 클래스 불러오는 방법
    - 클래스명과 괄호 안에는 필요한 변수들을 넣어주고 `data_processor` 변수명으로 선언
- 클래스의 함수나 변수를 사용하는 방법
    - `data_processor.함수명(또는 변수명)`을 선언

In [15]:
data = np.random.normal(0, 10, (5, 5))
target = np.random.normal(0, 1, 5)
print(data)
data_processor = DataPreprocessing(data, target)
data = data_processor.scaler('minmax')
print(data)

[[10.29841619 -4.52369192 15.37549818  3.97545762 -9.17115555]
 [ 4.88842302 11.62025543  2.24048304 -1.03505831 17.47825633]
 [-4.7432619  -5.3220069  -7.64560588 -4.41344159 -4.76287524]
 [24.42244854  0.44914417  2.59433146 -4.56839545  5.1209493 ]
 [-3.72515748  9.76491329 -5.04395495  4.82667957  9.82492904]]
[[0.51573159 0.04711974 1.         0.909397   0.        ]
 [0.33024002 1.         0.42943592 0.37608397 1.        ]
 [0.         0.         0.         0.01649309 0.16541755]
 [1.         0.34063639 0.44480653 0.         0.53630095]
 [0.03490758 0.8904903  0.11301156 1.         0.7128144 ]]


##### 💡 **클래스 상속**
- 클래스 상속을 통해 다른 클래스의 메서드를 모두 사용할 수 있다.
- `__init__`에 self만 적으면 함수가 안돌아가고 에러 발생하므로 필요한 변수명을 적어주어야 한다.
- 클래스 상속 방법
    - 상속받고자 하는 하위 클래스명 괄호 안에 상속을 해 주는 클래스명 입력
    - 여러개의 클래스 상속 가능(콤마로 여러 개의 상위 클래스명 입력)

In [16]:
class DataPipeline(DataPreprocessing) :
    def __init__(self, data) :
        self.data = data
        self.num_features = self.data.shape[1]
        
pipe = DataPipeline(data)
data = pipe.scaler('minmax')